### ISSUE TITLE
G6 Canvas Error when running Jest Tests 

### ISSUE THREAD

**Issue by barrycarr** [antvis/G6#1167]
* **G6 Version**:
3.2.9

* **Platform**:
Macbook Pro (15 inch. Mid 2015) with 16Gb RAM, MacOS Catalina 10.15.2
React version: 16.12.0
TypeScript: 3.7.5

* **Mini Showcase(like screenshots)**:
![Screenshot 2020-01-22 at 11 00 39](https://user-images.githubusercontent.com/280746/72888933-7d545b80-3d06-11ea-9d4d-3ae4fa57b970.png)

* **CodePen Link**:

Since installing and using G6 for use in our react/typescript project, I get the following error whenever I run Jest tests. Even installing canvas package, as recommended by the error message, does not fix the error. I've also tried canvas-prebuilt npm package but this made no difference either.  

Here is the error message: 
```
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
        at module.exports (/Users/barry/Development/pti/dms/frontend2/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at HTMLCanvasElementImpl.getContext (/Users/barry/Development/pti/dms/frontend2/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
        at HTMLCanvasElement.getContext (/Users/barry/Development/pti/dms/frontend2/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
        at Object.<anonymous> (/Users/barry/Development/pti/dms/frontend2/node_modules/@antv/g6/build/webpack:/[name]/g6.js:9:1)
        at e (/Users/barry/Development/pti/dms/frontend2/node_modules/@antv/g6/build/webpack:/[name]/g6.js:1:1)
        at Object.<anonymous> (/Users/barry/Development/pti/dms/frontend2/node_modules/@antv/g6/build/webpack:/[name]/g6.js:1:1)
        at e (/Users/barry/Development/pti/dms/frontend2/node_modules/@antv/g6/build/webpack:/[name]/g6.js:1:1)
        at Object.<anonymous> (/Users/barry/Development/pti/dms/frontend2/node_modules/@antv/g6/build/webpack:/[name]/g6.js:9:1)
        at e (/Users/barry/Development/pti/dms/frontend2/node_modules/@antv/g6/build/webpack:/[name]/g6.js:1:1)
        at Object.<anonymous> (/Users/barry/Development/pti/dms/frontend2/node_modules/@antv/g6/build/webpack:/[name]/g6.js:9:1) undefined
```

Package.json file:
```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@antv/g6": "^3.2.9",
    "@craco/craco": "^5.6.3",
    "antd": "^3.26.7",
    "autoprefixer": "^9.7.4",
    "babel-loader": "^8.0.6",
    "babel-preset-react-app": "^9.1.0",
    "case-sensitive-paths-webpack-plugin": "^2.3.0",
    "chalk": "^3.0.0",
    "classnames": "^2.2.6",
    "connected-react-router": "^6.6.1",
    "craco-antd": "^1.14.1",
    "css-loader": "^3.4.2",
    "datejs": "^1.0.0-rc3",
    "dotenv": "8.2.0",
    "dotenv-expand": "5.1.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "^5.0.2",
    "formik": "^2.1.2",
    "formik-antd": "^1.8.0",
    "fp-ts": "^2.4.1",
    "fs-extra": "8.1.0",
    "hoist-non-react-statics": "^3.3.1",
    "html-webpack-plugin": "3.2.0",
    "immer": "^5.3.2",
    "io-ts": "^2.0.6",
    "jsbarcode": "^3.11.0",
    "json2csv": "^4.5.4",
    "less": "^3.10.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "4.1.0",
    "postcss-loader": "3.0.0",
    "promise": "^8.0.3",
    "qrcode.react": "^1.0.0",
    "raf": "^3.4.1",
    "rc-upload": "^2.9.4",
    "react": "^16.12.0",
    "react-dev-utils": "^10.0.0",
    "react-dom": "^16.12.0",
    "react-intl": "^3.11.0",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.3.0",
    "recompose": "^0.30.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "resolve": "^1.15.0",
    "source-map-loader": "^0.2.4",
    "style-loader": "^1.1.3",
    "sw-precache-webpack-plugin": "^0.11.5",
    "ts-loader": "^6.2.1",
    "tsconfig-paths-webpack-plugin": "^3.2.0",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "url-loader": "^3.0.0",
    "webpack-manifest-plugin": "2.2.0",
    "whatwg-fetch": "3.0.0",
    "xlsx": "^0.15.4",
    "yup": "^0.28.0"
  },
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.8.3",
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@babel/preset-react": "^7.8.3",
    "@testing-library/react": "^9.4.0",
    "@testing-library/react-hooks": "^3.2.1",
    "@types/classnames": "^2.2.9",
    "@types/datejs": "0.0.30",
    "@types/enzyme": "^3.10.4",
    "@types/enzyme-adapter-react-16": "^1.0.5",
    "@types/fetch-mock": "^7.3.2",
    "@types/jest": "^24.9.0",
    "@types/json2csv": "^4.5.1",
    "@types/lodash": "^4.14.149",
    "@types/node": "^13.1.8",
    "@types/qrcode.react": "^1.0.0",
    "@types/react": "^16.9.18",
    "@types/react-addons-test-utils": "^0.14.25",
    "@types/react-dom": "^16.9.5",
    "@types/react-redux": "^7.1.6",
    "@types/react-router": "^5.1.4",
    "@types/react-router-dom": "^5.1.3",
    "@types/react-test-renderer": "^16.9.1",
    "@types/recompose": "^0.30.7",
    "@types/redux-logger": "^3.0.7",
    "@types/redux-mock-store": "^1.0.1",
    "@types/yup": "^0.26.27",
    "@typescript-eslint/eslint-plugin": "^2.17.0",
    "@typescript-eslint/parser": "^2.17.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "eslint": "^6.8.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-react": "^7.18.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "fetch-mock": "^8.3.1",
    "fork-ts-checker-webpack-plugin": "^3.1.1",
    "jest-fetch-mock": "^3.0.1",
    "jest-localstorage-mock": "^2.4.0",
    "less-loader": "^5.0.0",
    "mock-local-storage": "^1.1.11",
    "react-addons-test-utils": "^15.6.2",
    "react-test-renderer": "^16.12.0",
    "redux-devtools-extension": "^2.13.8",
    "redux-mock-store": "^1.5.4",
    "semantic-ui-react": "^0.88.2",
    "ts-jest": "^24.3.0",
    "typescript": "^3.7.5"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
  "main": "craco.config.js",
  "directories": {
    "test": "tests"
  },
  "repository": {
    "type": "git",
    "url": "git@git.pltnm.info:dms/frontend2.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by baizn** [comment]
can you provide a CodePen Link？

Jest Test Example

```
import G6 from '@antv/g6'

const container = document.createElement('div');
container.id = 'global-spec';
document.body.appendChild(container);

describe('graph', () => {
  const globalGraph = new G6.Graph({
    container: div,
    width: 500,
    height: 500,
    modes: {
      default: ['drag-node']
    }
  });

  it('invalid container', ()  => {
    expect(() => { new G6.Graph({}) }).toThrowError('invalid container')
  })
  
  it('new & destroy graph', () => {
    const inst = new G6.Graph({
      container,
      width: 500,
      height: 500,
      modes: {
        default: ['drag-node']
      }
    });
    const length = div.childNodes.length;

    expect(inst).not.toBe(undefined)
    expect(inst instanceof G6.Graph).toBe(true);
    expect(length > 1).toBe(true);

    expect(inst.get('canvas')).not.toBe(undefined)
    expect(inst.get('group')).not.toBe(undefined)

    expect(inst.get('group').get('className')).toEqual('root-container');
    expect(inst.get('group').get('id').endsWith('-root')).toBe(true);

    const children = inst.get('group').get('children');
    expect(children.length).toBe(4);
    expect(children[1].get('className')).toEqual('edge-container');
    expect(children[0].get('className')).toEqual('custom-group-container');

    const nodes = inst.getNodes();
    expect(nodes).not.toBe(undefined)
    expect(nodes.length).toBe(0);

    const edges = inst.getEdges();
    expect(edges).not.toBe(undefined)
    expect(edges.length).toBe(0);

    const canvas = inst.get('canvas');
    inst.destroy();

    expect(inst.destroyed).toBe(true)
    expect(canvas.destroyed).toBe(true);
    expect(length - div.childNodes.length).toBe(1);
  });
)}
```

**Comment by DercilioFontes** [comment]
You can try to use `jest-canvas-mock`
https://www.npmjs.com/package/jest-canvas-mock

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
