### ISSUE TITLE
G6 3.3.x 版本 Rollup 集成错误

### ISSUE THREAD

**Issue by gaoli** [antvis/G6#1260]
```jsx
import G6 from '@antv/g6';
```
编译时报错：

```
✖  error     Error: 'groupBy' is not exported by node_modules/_lodash@4.17.15@lodash/lodash.js 
    at error (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:9820:16)
    at handleMissingExport (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:9721:28)
    at Module.traceVariable (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:10159:24)
    at ModuleScope.findVariable (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:8766:39)
    at FunctionScope.findVariable (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:3065:38)
    at FunctionScope.findVariable (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:3065:38)
    at BlockScope.findVariable (/Users/gaoli/GitHub/GGEditor/node_modules/_rollup@1.31.1@rollup/dist/shared/node-entry.js:3065:38)
```

测试过之前的 3.2.x 版本没有发现此问题，应该是 3.3.x 升级之后才出现：）

**Comment by baizn** [comment]
@gaoli  把你最终解决方案在这里回复一下吧，后面如果有其他同学也遇到类似问题就可以参考了

**Comment by gaoli** [comment]
1. 添加 `babel-plugin-lodash` 插件，此插件会自动优化 `lodash` 的引用方式。
2. 设置 `@rollup/plugin-node-resolve` 插件  [browser](https://github.com/rollup/plugins/tree/master/packages/node-resolve#browser) 属性为 `true`，修复 G 当前的问题。
