### ISSUE TITLE
Jest test are failing with the upgrade to 4.1.13

### ISSUE THREAD

**Issue by JyotsnaC** [antvis/G6#2712]
- [x] I have searched the [issues](https://github.com/antvis/g6/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
When I run Jest tests I see below error. The test works perfectly with version 4.1.7 but it fails with any version above that

  ReferenceError: Worker is not defined

      25 | import {CUSTOM_ELEMENTS_SCHEMA} from "@angular/compiler/src/core";
      26 | import {ComponentFixture, fakeAsync, TestBed, tick,} from "@angular/core/testing";
    > 27 | import G6 from "@antv/g6";
         | ^
      28 | import {TranslateLoader, TranslateModule} from "@ngx-translate/core";
      29 | import {TranslateHttpLoader} from "@ngx-translate/http-loader";
      30 | import {APOLLO_TESTING_CACHE, ApolloTestingController, ApolloTestingModule,} from "apollo-angular/testing";

      at new WebWorker (node_modules/@antv/g6-pc/lib/layout/worker/work.js:16:5)
      at Object.<anonymous> (node_modules/@antv/g6-pc/lib/layout/worker/layout.worker.js:119:20)
      at Object.<anonymous> (node_modules/@antv/g6-pc/lib/graph/controller/layout.js:14:16)
      at Object.<anonymous> (node_modules/@antv/g6-pc/lib/graph/controller/index.js:21:38)
      at Object.<anonymous> (node_modules/@antv/g6-pc/lib/graph/graph.js:22:19)
      at Object.<anonymous> (node_modules/@antv/g6-pc/lib/index.js:104:37)
      at Object.<anonymous> (node_modules/@antv/g6/lib/index.js:13:37)
      at Object.<anonymous> (projects/hierarchy/src/app/page/topology/topology.component.spec.ts:27:1)

| Environment | Info |
|---|---|
| g6 | 4.1.13 |
| System | Mac Os latest |
| Browser | Chrome latest |

**Comment by baizn** [comment]
What is your single test environment?  [Worker](https://developer.mozilla.org/zh-CN/docs/Web/API/Worker) is not supported?

Execute the single test in the following file，It can work normally：
https://github.com/antvis/G6/blob/master/packages/pc/tests/unit/layout/circular-web-worker-spec.ts

![image](https://user-images.githubusercontent.com/9443867/110290006-2baf8300-8025-11eb-94a9-970168fb06ed.png)
