### ISSUE TITLE
服务端渲染，页面刷新后报错！求助！

### ISSUE THREAD

**Issue by gentleKun** [antvis/G6#2891]
我是用的服务端渲染g6页面，页面刷新时报错：
2021-05-15T17:55:15.701] [DEBUG] vue-ssr - renderToString: ReferenceError: self is not defined
    at Object.<anonymous> (/Users/test/myProjects/node_modules/@antv/algorithm/lib/workers/index.worker.js:18:11)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/test/myProjects/node_modules/@antv/algorithm/lib/workers/createWorker.js:10:37)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)

**Comment by DaphneChang** [comment]
遇到同一个问题啦，求助！

**Comment by SOVLOOKUP** [comment]
同样的问题，求助！！！

**Comment by SOVLOOKUP** [comment]
https://github.com/antvis/algorithm/blob/eba5caaa9ce65c77c1e5d0127c78d12301f2f1ab/packages/graph/src/workers/createWorker.ts

该依赖大量调用了浏览器的 worker \ window 等API导致无法进行SSR渲染，能否用异步函数进行修改？
