### ISSUE TITLE
graph layout failed, TypeError: el.getBBox is not a function

### ISSUE THREAD

**Issue by andreasnett** [antvis/G6#3111]
I have a react component that renders a g6 graph. This graph usually fetches data from redux and converts it to the `GraphData` type. This works fine.
When trying to pass data through as props like this
```javascript
graphData: {
  nodes: [{id: "1"}],
  edges: []
}
```
the graph.render() method causes this output
```
 graph layout failed, TypeError: el.getBBox is not a function
        at Rect.Object.<anonymous>.ShapeBase.calculateBBox (/Users/netteland/Kode/ponder/node_modules/@antv/g-svg/src/shape/base.ts:62:17)
        at Rect.Object.<anonymous>.AbstractShape.getBBox (/Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/shape.ts:29:19)
        at Rect.Object.<anonymous>.AbstractShape.calculateCanvasBBox (/Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/shape.ts:61:23)
        at Rect.Object.<anonymous>.AbstractShape.getCanvasBBox (/Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/shape.ts:38:25)
        at /Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/container.ts:131:27
        at Object.each (/Users/netteland/Kode/ponder/node_modules/@antv/util/src/each.ts:11:13)
        at Group.Object.<anonymous>.Container.getCanvasBBox (/Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/container.ts:130:7)
        at /Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/container.ts:131:27
        at Object.each (/Users/netteland/Kode/ponder/node_modules/@antv/util/src/each.ts:11:13)
        at Group.Object.<anonymous>.Container.getCanvasBBox (/Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/container.ts:130:7)
        at /Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/container.ts:131:27
        at Object.each (/Users/netteland/Kode/ponder/node_modules/@antv/util/src/each.ts:11:13)
        at Group.Object.<anonymous>.Container.getCanvasBBox (/Users/netteland/Kode/ponder/node_modules/@antv/g-base/src/abstract/container.ts:130:7)
        at ViewController.fitCenter (/Users/netteland/Kode/ponder/node_modules/@antv/g6-core/lib/graph/controller/view.js:41:22)
        at Graph.AbstractGraph.fitCenter (/Users/netteland/Kode/ponder/node_modules/@antv/g6-core/lib/graph/graph.js:597:20)
        at success (/Users/netteland/Kode/ponder/node_modules/@antv/g6-core/lib/graph/graph.js:1438:14)
        at /Users/netteland/Kode/ponder/node_modules/@antv/g6-pc/lib/graph/contro
```
When the edges array is nonempty, this throws an error. 

I am passing as props for testing purposes.

**Comment by Yanyan-Wang** [comment]
What browser are you using?

**Comment by andreasnett** [comment]
Chrome

**Comment by Yanyan-Wang** [comment]
please provide an online reproduced demo

**Comment by Yanyan-Wang** [comment]
Hi, dear user. Since there was no response for a long time, we cannot figure out the answer of the problem you described. If there is new progress, feel free to open a new issue.
