### ISSUE TITLE
Unable to parse color from object [247,249.7,255]

### ISSUE THREAD

**Issue by lonelyzou** [antvis/G6#3644]
### 问题描述

Unable to parse color from object [247,249.7,255]
    at new Color (index.js:49:1)
    at Color (index.js:11:1)
    at mixColor (color.js:13:15)
    at getColorsWithDefaultTheme (color.js:25:1)
    at getColorsWithSubjectColor (color.js:170:1)
    at Module../node_modules/@antv/g6-pc/es/global.js (global.js:5:41)
    at __webpack_require__ (bootstrap:832:1)
    at fn (bootstrap:129:1)
    at Module../node_modules/@antv/g6-pc/es/graph/graph.js (graph.js:1:1)
    at __webpack_require__ (bootstrap:832:1)

### 重现链接

无

### 重现步骤

代码
`<template>
  <div>
    <div id="container"></div>
  </div>
</template>

<script>
import G6 from '@antv/g6' // 在需要的js文件引入
export default {
  mounted () {
    this.initTree()
  },
  methods: {
    initTree () {
      const data = {
        nodes: [
          {
            id: 'node1',
            label: 'Circle1',
            x: 150,
            y: 150
          },
          {
            id: 'node2',
            label: 'Circle2',
            x: 400,
            y: 150
          }
        ]
      }

      const graph = new G6.Graph({
        container: 'container',
        width: 500,
        height: 500
      })

      graph.data(data)
      graph.render()
    }
  }
}
</script>`
进入页面直接报错

### 预期行为

不再报错，显示流程节点

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- Windows
- 网页浏览器: [Google Chrome, Safari, Firefox]
- Google Chrome
- G6 版本: [4.5.1 ... ]
- ^4.6.4

**Comment by Yanyan-Wang** [comment]
颜色的格式只支持三种形式的字符串：
-  16 进制，如 '#ffffff'
-  'rgb(255, 255, 255)'
-  'rgba(255, 255, 255, 1)'

**Comment by seveneElevenup** [comment]
> 颜色的格式只支持三种形式的字符串：
您好，这个问题有解决麻？
