### ISSUE TITLE
存在层级关系 Combo 收起子节点，此时调用 changeData 报错

### ISSUE THREAD

**Issue by simplejason** [antvis/G6#3902]
### Describe the bug

设置一个 combo A 的 parentId 为另一个 combo D，这时收起 A 后，手动触发 changeData(或者 data/read) 报错
```
Uncaught (in promise) TypeError: bboxMethod is not a function
    at ShapeBase.calculateBBox (base.ts:44:17)
    at AbstractShape.getBBox (shape.ts:29:19)
    at getBBox (graphic.js:30:22)
    at Combo.calculateCanvasBBox (combo.js:84:37)
    at Combo.getBBox (combo.js:279:21)
    at Node.getLinkPoint (node.js:150:21)
    at Edge.getLinkPoint (edge.js:91:29)
    at Edge.getShapeCfg (edge.js:189:27)
    at ItemBase.updateShape (item.js:722:28)
    at ItemBase.refresh (item.js:651:10)
```

### Your Example Website or App

https://stackblitz.com/edit/react-r4cocg?file=index.js,index.html

### Steps to Reproduce the Bug or Issue

1、收起 Combo A
2、点击 `Change Data` 按钮
3、控制台报错

### Expected behavior

正常渲染并进入 afterlayout 等事件周期

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Yanyan-Wang** [comment]
v4.7.1 已修复

**Comment by dfiai** [comment]
I have the same problem,

```
base.ts:44 Uncaught TypeError: bboxMethod is not a function
    at ShapeBase3.calculateBBox (base.ts:44:17)
    at AbstractShape2.getBBox (shape.ts:29:19)
    at getBBox2 (graphic.js:14:22)
    at Combo2.calculateCanvasBBox (combo.js:65:16)
    at Combo2.getBBox (combo.js:220:21)
    at Node3.getLinkPoint (node.js:109:21)
    at Edge3.getLinkPoint (edge.js:64:29)
    at Edge3.getShapeCfg (edge.js:142:27)
    at ItemBase2.updateShape (item.js:599:28)
    at ItemBase2.refresh (item.js:538:10)
```
