### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by newZhaoZilong** [antvis/G6#4143]
### Describe the bug

vue-router.mjs:3451 ReferenceError: require is not defined
    at eval (index.js:4:31)
    at ./node_modules/d3-interpolate/src/index.js (node_modules_antv_g6_es_index_js.488c699d8a83ad8ab376.js:15934:1)
    at __webpack_require__ (remoteEntry.js:102:33)
    at fn (remoteEntry.js:501:21)
    at eval (timeline.ts?6429:3:1)
    at ./node_modules/@antv/g-base/esm/animate/timeline.js (node_modules_antv_g6_es_index_js.488c699d8a83ad8ab376.js:931:1)
    at __webpack_require__ (remoteEntry.js:102:33)
    at fn (remoteEntry.js:501:21)
    at eval (canvas.ts?6eea:6:1)
    at ./node_modules/@antv/g-base/esm/abstract/canvas.js (node_modules_antv_g6_es_index_js.488c699d8a83ad8ab376.js:865:1)

### Your Example Website or App

https://codesandbox.io/s/sleepy-zhukovsky-ldcjop?file=/src/components/HelloWorld.jsx

### Steps to Reproduce the Bug or Issue

这两天突然出现的，之前都没问题

### Expected behavior

跟之前一样

### Platform

Browser vue3  "@antv/g6": "^4.7.17"

**Comment by Yanyan-Wang** [comment]
尝试用 yarn 安装

**Comment by newZhaoZilong** [comment]
vue.config.js里使用
transpileDependencies: ["@antv/*"]
好像把问题解决了
