### ISSUE TITLE
window10下运行和打包site报错

### ISSUE THREAD

**Issue by dargon5210** [antvis/G6#4217]
### 问题描述

window10下运行和打包site报错，fatal - Error: ERROR in E:workspaceG6
ode_modules@antvdumi-theme-antvdistcontext.js
Module build failed: UnhandledSchemeError: Reading from "E:workspaceG6
ode_modules@antvdumi-theme-antvdistcontext.js" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "e:" URIs.
    at E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:83424:25
    at Hook.eval [as callAsync] (eval at create (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7682), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:4851)
    at Object.processResource (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:83421:8)
    at processResource (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:35822:11)
    at iteratePitchingLoaders (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:35773:10)
    at runLoaders (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:36000:2)
    at NormalModule._doBuild (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:83411:3)
    at NormalModule.build (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:83555:15)
    at E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:57540:12
    at NormalModule.needBuild (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:83845:32)
    at Compilation._buildModule (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:57521:10)
    at E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:157380:10
    at Hook.eval [as callAsync] (eval at create (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7682), <anonymous>:6:1)
    at AsyncQueue._startProcessing (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:157370:26)
    at AsyncQueue._ensureProcessing (E:\workspace\G6\node_modules\@umijs\preset-umi\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:157357:12)
    at processImmediate (internal/timers.js:464:21)
 @ ./.dumi/tmp-production/theme-antv/ContextWrapper.tsx 6:0-102 13:27-52
 @ ./.dumi/tmp-production/core/route.tsx 1633:23-188
 @ ./.dumi/tmp-production/umi.ts 10:0-41 27:17-26

### 重现链接

https://stackblitz.com/

### 重现步骤

yarn
yarn build:all
yarn build:site

### 预期行为

修复bug

### 平台

- 操作系统: Windows10
- 网页浏览器: Google Chrome108
- G6 版本: 4.8.3

### 屏幕截图或视频（可选）

![image](https://user-images.githubusercontent.com/21213337/213108635-df55435c-61bf-45b9-b253-fc4262228d55.png)

**Comment by Yanyan-Wang** [comment]
感谢报告，年后复工了我找 dumi 的负责人看看

**Comment by dargon5210** [comment]
> 感谢报告，年后复工了我找 dumi 的负责人看看

好的 谢谢

**Comment by leechor** [comment]
这个有后续吗?

**Comment by mioxs** [comment]
是否可以提供打包好的离线文档，window10无法打包

**Comment by mioxs** [comment]
你好@Yanyan-Wang ，是否可以提供打包好的离线文档（最好放到page分支），window10无法打包。
