### ISSUE TITLE
layout failed Error: Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by loveshiun** [antvis/G6#4893]
### Describe the bug

```
layout failed Error: Failed to execute 'postMessage' on 'Worker': function (e) {
    obj[action](e);

  } could not be cloned.

    at LayoutController.runWebworker (https://4dmzm8.csb.app/node_modules/@antv/g6-pc/es/graph/controller/layout.js:432:14)

    at eval (https://4dmzm8.csb.app/node_modules/@antv/g6-pc/es/graph/controller/layout.js:397:22)

```

### Your Example Website or App

https://codesandbox.io/s/cocky-euler-4dmzm8?file=/index.js

### Steps to Reproduce the Bug or Issue

1. Try to comment out the 3 lines after `console.log("try to update the graph");` (line: 182 in the example link)
```
    graph.data(newData);
    graph.render();
    graph.updateItem(graph.getNodes()[0], config);
```
the graph works as expected.

1. Add back the 3 lines, the graph will not update.

1. Keep the 3 lines, but change `workerEnabled` from true to false, the graph will update normally again.

1. Set `workerEnabled` to true again, but now add one more line `graph.render();` after the 3 lines, the graph will also update.

Besides, when `workerEnabled` is true, some operations may result in `layout failed Error: Failed to execute 'postMessage' on 'Worker'`.

### Expected behavior

When `workerEnabled: true`, should have nearly the same behavior as `workerEnabled: false`?

### Platform

- OS: Linux
- Browser: Chrome (incognito)
- Version: 

The example app is updated from [https://codesandbox.io/s/0vg0cl](https://codesandbox.io/s/0vg0cl)

**Comment by loveshiun** [comment]
@Yanyan-Wang Thank you! 😊
