### ISSUE TITLE
vue2 "@antv/g6": "^4.8.24"  ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by iOSHw** [antvis/G6#5763]
### Describe the bug

本地运行没问题，发布到 test 环境编译没抱错，运行报错
vue-router.esm.js:2314 ReferenceError: exports is not defined
    at ./node_modules/tslib/tslib.es6.mjs (index.js:21:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/@antv/g6-pc/es/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/@antv/g6/es/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/CbSalesRuleG6/RuleLook.vue?vue&type=script&lang=js& (RuleLook.vue:12:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/components/CbSalesRuleG6/RuleLook.vue?vue&type=script&lang=js& (index.vue:1:244)
    at __webpack_require__ (bootstrap:19:1)
![image](https://github.com/antvis/G6/assets/17612722/9afebc0c-fa4e-43ec-9215-a1cbb8ddd4ab)

### Your Example Website or App

https://ops.yaochanchan.com

### Steps to Reproduce the Bug or Issue

运行不报错，打包后报错

### Expected behavior

![image](https://github.com/antvis/G6/assets/17612722/4a9e448f-a671-45b0-a242-6eb726be858b)

### Platform

vue2 
"@antv/g6": "^4.8.24"

**Comment by Aarebecca** [comment]
打包问题请自行解决哈

**Comment by dingcang** [comment]
怎么解决的最后
