### ISSUE TITLE
An error is reported when you use WorkEnable

### ISSUE THREAD

**Issue by WangHanZ** [antvis/G6#6529]
### Describe the bug / 问题描述

layout failed DOMException: Failed to execute 'postMessage' on 'Worker': function () { } could not be cloned.
    at LayoutController.runWebworker (webpack-internal:///./node_modules/@antv/g6-pc/es/graph/controller/layout.js:500:14)
    at eval (webpack-internal:///./node_modules/@antv/g6-pc/es/graph/controller/layout.js:455:22)

将layout.min.js放在了dcn地址也可以访问 到这个layout.min.js文件，
   this.topoGraph.data({
            nodes: obj.nodes,
            edges: obj.edges
          })
          this.topoGraph.updateLayout({
            type: 'force2',
            clustering: true,
            animate: false,
            nodeClusterBy: 'comboId',
            linkDistance: 20, // 可选，边长
            nodeStrength: 60, // 可选
            nodeSize: 10,
            edgeStrength: 15,
            workerEnabled: true,
            workerScriptURL: `${window.location.origin}/layout.min.js`,

            onLayoutEnd: () => { // 可选
              this.topoGraph.fitCenter()
            }
          })
          this.topoGraph.render()

但是执行得时候汇报这个错误

### G6 Version / G6 版本

4.x

### Operating System / 操作系统

Windows

### Browser / 浏览器

Chrome

**Comment by yvonneyx** [comment]
感谢你的反馈，也感谢耐心等待 🙏 

你提到的这个问题已经在 `@antv/g6@5.1.0-beta.0` 中支持了，欢迎升级试用看看～目前相关的使用方式和 API 可以先参考 Layout 官网文档： 👉 https://layout.antv.vision/zh 等 G6 正式版发布后，我们也会同步更新到 G6 官网。

如果在升级或使用过程中遇到任何问题，或者有新的想法，欢迎随时再提 issue 一起讨论。非常感谢你的支持！

---

Thanks for the feedback, and thanks for your patience 🙏 

The issue you mentioned is now supported in `@antv/g6@5.1.0-beta.0`. Feel free to upgrade and give it a try. For now, you can refer to the Layout website for usage details and API docs: 👉 https://layout.antv.vision. The documentation will also be synced to the G6 website once the official G6 release is out.

If you run into any issues during the upgrade or have new ideas to share, feel free to open a new issue and discuss with us. Thanks a lot for your support!
